### PR TITLE
Update readme.md (Breakfast - Title & Notes)

### PR DESCRIPTION
**Pull request by ahurley7**
- Updated recipe title for breakfast file (i.e. Chocolate Chip Pancakes)
- Updated Notes section with URL to recipe source

## 🎯 Objective

Updating breakfast recipe file in accordance with agreed allocation of team responsibilities

## 🛠️ Changes made

- Updated breakfast recipe to read "Chocolate Chip Pancakes"
- Updated "Notes" section to show URL for recipe source (i.e. https://www.food.com/recipe/chocolate-chip-pancakes-45935)
- Updated Codemates team number and team membership

## 👥 Who needs to review this Pull Request? 

Code reviews requested from: @jahnavishah121-coder and @annakim222 

- Please use this forum to address any issues that are discovered in the subsequent review
- Approvals by 2 independent team members are required to execute merge action to master branch.

### CODE REVIEW

**Comment by URIELGSN** [comment]
Reviewed, no issues

**Review by URIELGSN — APPROVED** [review]
approve

**Review by annakim222 — APPROVED** [review]
Review/no issues

**Comment by annakim222** [comment]
Two approvals given - confirm merge

**Pull request merged**
