### PR TITLE
update readme.md (Breakfast-equipment)

### PR DESCRIPTION
**Pull request by romolina94**
I added the equipment for chocolate chip pancakes

## 🎯 Objective

Submitting pull request for Classroom learning

## 🛠️ Changes made

Updated the equipment section for Chocolate Pancakes

## 👥 Who needs to review this Pull Request? 

Review request from:
@ahurley7 
@URIELGSN

### CODE REVIEW

**Review by ahurley7 — APPROVED** [review]
Reviewed - no issues found.  Approved

**Comment by romolina94** [comment]
Reviewed - no issues found. Approved

**Review by URIELGSN — APPROVED** [review]
no issues - approve

**Comment by URIELGSN** [comment]
two approvals have reviewed - merge request will proceed

**Pull request merged**
