### PR TITLE
README UPDATE - breakfast

### PR DESCRIPTION
**Pull request by URIELGSN**
time to prepare

## 🎯 Objective

learning

## 🛠️ Changes made

added time to prepare

## 👥 Who needs to review this Pull Request? 

review requested from @romolina94 @ahurley7

### CODE REVIEW

**Comment by romolina94** [comment]
Reviewed, no issues found, approved

**Review by romolina94 — APPROVED** [review]
Reviewed - no issues found. Approved

**Review by ahurley7 — APPROVED** [review]
Reviewed proposed changes - no errors.  Approved

**Comment by ahurley7** [comment]
Secured 2 approved code reviews as required.  Merging change with the main branch

**Pull request merged**
