### PR TITLE
Update readme - dinner

### PR DESCRIPTION
**Pull request by annakim222**
updated ingredients for steak

## 🎯 Objective

classroom learning for pull requests

## 🛠️ Changes made

updated ingredients lists in dinner recipe

## 👥 Who needs to review this Pull Request? 

review requested from @ahurley7 and @romolina94

### CODE REVIEW

**Comment by romolina94** [comment]
Reviewed - no issues found. Approved

**Review by romolina94 — APPROVED** [review]
Reviewed - no issues found. Approved

**Review by ahurley7 — APPROVED** [review]
Reviewed the added ingredients list - no issues found.  Approved

**Comment by ahurley7** [comment]
2 approvals secured in code review.  Move to merge approved

**Pull request merged**
