### PR TITLE
Update readme.md (Dinner - Preparation Steps)

### PR DESCRIPTION
**Pull request by ahurley7**
The following updates are requested for the Dinner readme file:
     1.  Changed dinner recipe title
     2.  Updated preparation steps
     3.  Added recipe source link
     4.  Updated team identification and member names

## 🎯 Objective

Updating dinner recipe file in accordance with agreed allocation of team responsibilities

## 🛠️ Changes made

1.  Updated dinner recipe title to "Strip Steak au Poivre"
2.  Added a total of 10 preparation steps with required formatting for clean reading.
3.  Updated "Notes" section with URL link to the recipe source (https://www.bonappetit.com/recipe/strip-steak-au-poivre)
4.  Indicated Codemates Team number and team member names at the foot of the document.

## 👥 Who needs to review this Pull Request? 

Code reviews requested from: @URIELGSN and @romolina94 
- Please use this forum to address an issues that are discovered in the subsequent review
- Approvals by 2 independent team members are required to execute merge action to master branch.

### CODE REVIEW

**Comment by ahurley7** [comment]
**As a follow-up to my pull request, the following oversight should be noted:**
- I failed to update the dinner recipe title as stated in the "Changes Made" section:
     - Dinner recipe should be "_Strip Steak au Poivre_"
     - I propose to leave this issue unchanged as it will provide Jahnavi a field to edit (i.e. ensuring everyone has an opportunity 
       to update the dinner text file per the assignment instructions.)

**Review by romolina94 — APPROVED** [review]
Love the recipe

**Review by URIELGSN — APPROVED** [review]
Top performer

**Comment by ahurley7** [comment]
Merge completed after required reviews by 2 team members

**Pull request merged**
